apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: prod
  name: my-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 30
    healthyThreshold: 1
    unhealthyThreshold: 5
    port: 80
    type: HTTP
    requestPath: /

