apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    name: mysql-secret
    app: mysql-gke-dev
  namespace: dev
type: Opaque
stringData:
  root-password: "test-password"
  

            env:
            - name: WORDPRESS_DB_HOST
              value: mysql-gke-dev:3306
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: WORDPRESS_DB_NAME
              value: wordpress  # ระบุชื่อฐานข้อมูลที่คุณต้องการใช้