apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  MYSQL_ROOT_PASSWORD: mysql-root-password
  MYSQL_DATABASE: database-wordpress
  MYSQL_USER: wordpress-user
  MYSQL_PASSWORD: wordpress-password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: default
data:
  WORDPRESS_DB_HOST : mysql-service
  WORDPRESS_DB_NAME : database-wordpress
  WORDPRESS_DB_USER : wordpress-user
  WORDPRESS_DB_PASSWORD : wordpress-password
