apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql-password-dev
        - name: MYSQL_DATABASE
          value: wordpress-database-dev
        - name: MYSQL_USER
          value: wordpress-user-dev
        - name: MYSQL_PASSWORD
          value: database-password-dev