apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service.dev.svc.cluster.local
        - name: WORDPRESS_DB_USER2
          value: wordpress-user-prod
        - name: WORDPRESS_DB_PASSWORD2
          value: database-password-prod
        - name: WORDPRESS_DB_NAME2
          value: wordpress-database-prod
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
