apiVersion: v1
kind: Service
metadata:
  name: mysql-service-prod
  namespace: prod
spec:
  type: ExternalName  # ปรับเป็น ExternalName
  externalName: mysql-service.dev.svc.cluster.local
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
