apiVersion: v1
kind: PersistentVolume
metadata:
  name: cs-fuse-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: cs-fuse-demo #does not need to refer to an existing StorageClass object
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=3003
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: mind-gcs-fuse-demo-bucket
    readOnly: false #optional
