apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-fuse-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: cs-fuse-pv
  storageClassName: cs-fuse-demo