apiVersion: v1
kind: Service
metadata:
  name: wordpress-service-prod
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
