apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          env:
            - name: WORDPRESS_DB_NAME
              value: wordpress-database-dev
            - name: WORDPRESS_DB_USER
              value: wordpress-user-dev
            - name: WORDPRESS_DB_PASSWORD
              value: database-password-dev
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service-prod
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
